exports.seed = function(knex: any) {
  // Deletes ALL existing entries
  return knex('products').del()
    .then(function () {
      // Inserts seed entries
      return knex('products').insert(
        products.map(product => {
          return {
            ...product,
            created_at: new Date(),
            updated_at: new Date(),
          }
        })
      )
  })
}

const products = [
  {
    name: "OKdo Metal Case for ROCK 5",
    description: "This nifty case from Radxa is tailor-made for the ROCK 5 Model B single board computer. It’s a robust metal case built to provide protection to your board whilst allowing easy access to all the ROCK 5B’s ports and PINs. It features an integrated heatsink, which provides passive cooling to your board ensuring your ROCK 5B will stay cool and keep ROCKing under the most demanding conditions",
    barcode: '985695845869',
    image: 'product_01.jpg',
    stock: 5,
    price: 670,
    category_id: 1,
    user_id: 1,
    status_id: 1,
  },
  {
    name: 'BBC micro:bit V2.0 Go Bundle',
    description: 'บอร์ด BBC micro:bit V2 ซึ่งพัฒนามาจาก V1 โดยใช้ไมโครคอนโทรลเลอร์ขนาดเล็กใช้ชิพ Nordic nRF52833 ARM Cortex-M4 พร้อม Bluetooth Low Energy 5.0 เป็นหลัก บนบอร์ดยังประกอบด้วยชิพเซ็นเซอร์หลายตัว ได้แก่ LSM303AGR(3-axis accelerometer ,3-axis magnetometer) , MLT-8530 (Speaker), Touch sensorและมี Microphone บนบอร์ด นอกจากนี้ยังมี LED 25 ดวง เรียงเป็น array5x5 ปุ่มกด 2 ปุ่ม พอร์ต Micro USB พอร์ต JST battery connector และ 23-pin edge connector เป็น GPIO ต่างๆ เช่น Digital I/O Analog Input PWM Serial I/O SPI และ I2C',
    barcode: '8754965845236',
    image: 'product_02.jpg',
    stock: 10,
    price: 830,
    category_id: 1,
    user_id: 1,
    status_id: 1,
  },
  {
    name: "Power Management HAT for Raspberry Pi",
    description: "The Power Management HAT is a smart power bank designed for Raspberry Pi. With the embedded Arduino MCU and RTC, the HAT features auto power management function which allows the Pi to work more power-efficient and more safely\nIf you're looking for some convenient utilities for yor long-term working Raspberry Pi, such as longer battery life, or auto power on-off control, this Power Management HAT would be the ideal choice\nBy auto starting up on specified period, and auto shutdown at other time, the HAT can greatly save the battery life. It will monitors the operating voltage/current status of the Raspberry Pi in real time, and can be configured to shut the Pi down according to the operating status. What's more, it comes with a handy power switch for easy on or off (safely shutdown the Pi by software), to avoid data loss caused by unplugging the power supply",
    barcode: '9854569585214',
    image: 'product_03.jpg',
    stock: 2,
    price: 740,
    category_id: 1,
    user_id: 1,
    status_id: 1,
  },
  {
    name: "Tony SX DC2 DC to DC module",
    description: "Tony SX DC2 DC to DC module เป็นบอร์ดจ่ายพลังงานของ Tony SX โดยรับอินพุตไฟฟ้ากระแสตรงแรงดันช่วง 9 ถึง 24 โวลต์ แล้วแปลงเป็นแรงดันกระแสตรงขนาด 5 โวลต์ จ่ายกระแสได้สูงสุด 3 แอมป์ เพื่อจ่ายให้กับบอร์ด Tony SX ESP32 Pro board บนบอร์ดยังมีรีเลย์จำนวน 2 ช่องที่สามารถควบคุมการเปิด-ปิดได้โดยใช้ IO14 และ IO15",
    barcode: '8523695845698',
    image: 'product_04.jpg',
    stock: 8,
    price: 340,
    category_id: 1,
    user_id: 1,
    status_id: 1,
  },
  {
    name: "Stm8",
    description: "Stm8",
    barcode: '745896521236',
    image: 'product_05.jpg',
    stock: 12,
    price: 590,
    category_id: 1,
    user_id: 1,
    status_id: 1,
  },
  {
    name: "Heatsink Cooling Fan for LattePanda",
    description: "Is your LattePanda running hot and throttling? This heat sink and fan combo will cool the CPU for smooth performance.\nThe fan keeps the unit running at a stable temperature. The 2-Pin jumper wire makes it easily to connect with the CN2 headers on the board.\n\nThis fan is low noise and has a thermal pad on the back that can stick on the metal shield on the board. With its aluminum casing, heat from CPU will be absorbed fast, giving you better performance. This is a simple and effective way to make the LattePanda cool!",
    barcode: '6541235896547',
    image: 'product_06.jpg',
    stock: 3,
    price: 590,
    category_id: 1,
    user_id: 1,
    status_id: 1,
  },
  {
    name: "Starter Sensor Set for LattePanda",
    description: "If you want to use your LattePanda for physical computing, this kit is the perfect choice to get started! You dont need a PhD degree in electronic engineering to use it - it is aimed at tinkerers who like to experiment and play. Every sensor comes with a LattePanda-compatible Gravity interface connector, so no need to worry about compatibility issues\n\nThe LattePanda Starter Sensor Set is a DFRobot Gravity series product. The DFRobot Gravity Series is an open-source, plug and play electronics toolkit for anyone to create anything. With dozens of standardized functional modules and powerful expansion boards, Gravity Series allows users of any skill level to easily connect, mix and develop their own projects that are compatible with Arduino and other microcontroller platforms. Click here to learn more about this product series",
    barcode: '7788954215556',
    image: 'product_07.jpg',
    stock: 5,
    price: 2520,
    category_id: 1,
    user_id: 1,
    status_id: 1,
  },
  {
    name: "Raspberry Pi Zero",
    description: "บอร์ด Raspberry Pi ขนาดเล็กเพียงครึ่งหนึ่งของบอร์ด Model A+ ใช้ชิพ Broadcom BCM2835 ARM11 ตัวเดียวกับ Raspberry Pi Model B/A+/B+ รันที่ความเร็ว 1 GHz (ปกติรันที่ 700 MHz) มี RAM LPDDR2 ขนาด 512 MB ช่องใส่ micro SD card พอร์ต mini HDMI พอร์ต micro USB สำหรับจ่ายไฟและ micro USB OTG / Host สำหรับต่ออุปกรณ์ พร้อมขา GPIO 40 ขาของ Raspberry Pi และพอร์ต CSI Camera Interface สำหรับต่อกล้อง Raspberry Pi Camera (เป็นพอร์ตขนาดเล็กต้องใช้สายแปลง)\n\nThe Raspberry Pi Zero is half the size of a Model A+, with twice the utility. A tiny Raspberry Pi that’s affordable enough for any project!",
    barcode: '7458956254125',
    image: 'product_08.jpg',
    stock: 2,
    price: 650,
    category_id: 1,
    user_id: 1,
    status_id: 1,
  },
  {
    name: "Raspberry Pi NoIR Camera V2 (8MP)",
    description: "Raspberry Pi HD Pi NoIR Camera Board V2 The Raspberry Pi HD Pi NoIR Camera Board connects to any Raspberry Pi or Compute Module, allowing you to create HD video and still photographs. The Pi NoIR (No Infrared) is the same as the standard camera module but without an IR filter. Therefore it is great for photography and video in the dark.The module utilises the IMX219PQ image sensor from Sony which offers high-speed video imaging and high sensitivity.\n\nThe Pi NoIR module offers reduced image contamination such as fixed pattern noise & smearing. It also features automatic control functions such as exposure control, white balance & luminance detection",
    barcode: '875965214569',
    image: 'product_09.jpg',
    stock: 20,
    price: 1170,
    category_id: 1,
    user_id: 1,
    status_id: 1,
  },
  {
    name: "Aluminium Armour Case with Dual Fan for Raspberry Pi 4",
    description: "By auto starting up on specified period, and auto shutdown at other time, the HAT can greatly save the battery life. It will monitors the operating voltage/current status of the Raspberry Pi in real time, and can be configured to shut the Pi down according to the operating status. What's more, it comes with a handy power switch for easy on or off (safely shutdown the Pi by software), to avoid data loss caused by unplugging the power supply",
    barcode: '8542369587459',
    image: 'product_10.jpg',
    stock: 15,
    price: 500,
    category_id: 1,
    user_id: 1,
    status_id: 1,
  },
  {
    name: "Power Management HAT for Raspberry Pi",
    description: "The Power Management HAT is a smart power bank designed for Raspberry Pi. With the embedded Arduino MCU and RTC, the HAT features auto power management function which allows the Pi to work more power-efficient and more safely.\n\nIf you're looking for some convenient utilities for yor long-term working Raspberry Pi, such as longer battery life, or auto power on-off control, this Power Management HAT would be the ideal choice\n\nBy auto starting up on specified period, and auto shutdown at other time, the HAT can greatly save the battery life. It will monitors the operating voltage/current status of the Raspberry Pi in real time, and can be configured to shut the Pi down according to the operating status. What's more, it comes with a handy power switch for easy on or off (safely shutdown the Pi by software), to avoid data loss caused by unplugging the power supply",
    barcode: '741258652365',
    image: 'product_11.jpg',
    stock: 12,
    price: 740,
    category_id: 1,
    user_id: 1,
    status_id: 1,
  },
  {
    name: "2-ch Isolate RS485 Exp. HAT",
    description: "โมดูล RS485 รองรับสัญญาณ 2 ช่อง ใช้งานบน Raspberry Pi ออกแบบมาเพื่อให้ใช้งานง่าย โดยเชื่อมต่อผ่านทาง   SPI interface เสียบใช้งานบน 40PIN GPIO\n\nThis is a 2-channel isolated RS485 expansion HAT designed for Raspberry Pi, adopts the SC16IS752+SP3485 solution, with embedded protection circuits such as power supply isolation, ADI magnetical isolation, and TVS diode, etc\n\nIt is easy to control the 2-channel RS485 for auto transceiving via SPI interface. Due to its fast communication, stability, reliability, and safety, it is an ideal choice for fields like industrial automation",
    barcode: '8745236525896',
    image: 'product_12.jpg',
    stock: 8,
    price: 700,
    category_id: 1,
    user_id: 1,
    status_id: 1,
  },
  {
    name: "3G HAT Expansion for Raspberry Pi",
    description: "3G Expansion บอร์ดเสริมสำหรับ Raspberry Pi มาในรูปแบบคล้าย HAT สามารถเสียบเข้ากับ Pin Header 40-pin และเชื่อมต่อสาย Micro USB เพื่อใช้งานเหมือนเป็น USB 3G Air Card รวมกับ USB GNSS (GPS/GLONASS) ในตัวเดียว ใช้ชิพสื่อสารผ่านเครือข่ายโทรศัพท์เคลื่อนที่จาก Quectel รุ่น UC20-G รองรับคลื่นความถี่ 800/850/900/1900/2100 MHz ในระบบ 3G UMTS และรองรับคลื่นความถี่ 850/900/1800/1900 ในระบบ 2G GSM ความเร็วในการสื่อสารข้อมูลสูงสุดแบบ HSPA+ ที่ 14.4 Mbps (downlink) และ 5.76 Mbps (uplink) พร้อมโมดูลรับสัญญาณ GNSS รองรับดาวเทียม GPS และ GLONASS\n\n3G Expansion for Raspberry Pi (UC20-G) เป็นบอร์ดสื่อสารเครือข่ายโทรศัพท์เคลื่อนที่ระบบ 3G ใช้โมดูลสื่อสารยี่ห้อ Quectel รุ่น UC20-G รองรับความถี่ 800/850/900/1900/2100 MHz ในระบบ UMTS (3G) และรองรับความถี่ 850/900/1800/1900 MHz ในระบบ GSM (2G) มีความเร็วในการสื่อสารข้อมูลสูงสุดระหว่างโมดูลกับเครือข่ายที่ 14.4 Mbps Downlink และ 5.76 Mbps Uplink เมื่อเชื่อมต่อกับเครือข่าย 3G โมดูลมาพร้อมตัวรับสัญญาณระบบนำร่องด้วยดาวเทียม (Global Navigation Satellite System: GNSS) รองรับช่องสื่อสาร GPS จำนวน 16 ช่องและช่องสื่อสาร GLONASS จำนวน 14 ช่อง พร้อมเทคโนโลยี SBAS (WAAS EGNOS MSAS) และ AGNSS (Support XTRA Technology) เหมาะสำหรับผู้ที่ต้องการทำให้ระบบเชื่อมต่อกับเครือข่าย 3G หรือผู้ที่ต้องการอัพเกรดระบบจาก 2G เป็น 3G ที่มีฟังก์ชันการใช้งานครอบคลุมทั้งการสื่อสารและระบุพิกัด สามารถนำไปประยุกต์ใช้ในงานต่างๆ เช่น ระบบขนส่งและติดตามตำแหน่งรถบรรทุกสินค้า มิเตอร์อัจฉริยะ จุดขายสินค้าไร้สาย การรักษาความปลอดภัย งานด้านสาธารณะสุข การติดตามบุคคลหรือสิ่งของ การควบคุมและบำรุงรักษาทางไกล เป็นต้น",
    barcode: '4452365698563',
    image: 'product_13.jpg',
    stock: 13,
    price: 1520,
    category_id: 1,
    user_id: 1,
    status_id: 1,
  },
  {
    name: "Stacking Header for Raspberry Pi",
    description: "Stack multiple plates, breakouts etc onto your Raspberry Pi Model B+ with this custom-made extra-tall and extra-long 2x20 female header. The female header part has extra spaces to make it 23mm tall: when placed on your Pi, a PCB will clear the Ethernet and USB jacks. The stacky pin part is also extra-long, 10mm, so that when a standard 1.5mm thickness PCB is installed, there will be 8.5mm remaining, plenty to plug into",
    barcode: '789632562546',
    image: 'product_14.jpg',
    stock: 25,
    price: 140,
    category_id: 1,
    user_id: 1,
    status_id: 1,
  },
  {
    name: "Gravity IO Expansion Shield for LattePanda",
    description: "บอร์ด Gravity IO Expansion Shield for LattePanda เป็นบอร์ดแปลงขา I/O ของ Arduino Leonardo บน LattePanda ให้เรียงขาแบบ R3 ของ Arduino ทำให้สามารถใส่ Shield ของ Arduino ได้ มาพร้อมขาคอนเนคเตอร์สำหรับเสียบโมดูล Gravity ของ DFRobot แบบ Digital (สีเขียวตัวอักษร D) และ Analog สีน้ำเงินตัวอักษร Aมีวงจร Regulator บนบอร์ดสำหรับเสียบแหล่งจ่ายแรงดันกระแสตรง 7-12 โวลต์ เพื่อจ่ายไฟให้ LattePanda และ Shield กับอุปกรณ์ Gravity ที่มาเชื่อมต่อได้\n\nThis Gravity I/O expansion shield, which is made for LattePanda, breakouts all GPIO pins to make it compatible with standard Arduino device and no interruption with other ports on LattePanda. Each pin has VCC and GND power port, compatible with Gravity-3Pin Color coded interface, supports hundreds of sensors and modules. ",
    barcode: '852323252365',
    image: 'product_15.jpg',
    stock: 2,
    price: 490,
    category_id: 1,
    user_id: 1,
    status_id: 1,
  },
  {
    name: "e-Paper Display HAT for Raspberry Pi",
    description: "This is an E-Ink display HAT for Raspberry Pi, 2.7-inch, 264x176 resolution, with embedded controller, communicating via SPI interface, supports red, black, and white three-color display.\n\nDue to the advantages like ultra low power consumption, wide viewing angle, great effect under sunlight, it is an ideal choice for applications such as shelf label, industrial instrument, and so on",
    barcode: '965325698547',
    image: 'product_16.jpg',
    stock: 10,
    price: 800,
    category_id: 1,
    user_id: 1,
    status_id: 1,
  },
  {
    name: "Miniature 5V Cooling Fan for Raspberry Pi",
    description: "Looking for another way to keep your Raspberry Pi cool? Hook up this 5V Mini Cooling Fan and prevent your hard-working Pi from overheating! Of course, it's also great for use with any small computer or FPGA or motor driver or anything that needs cooling.\n\nPlug the fan directly into your Raspberry Pi's 5V+GND GPIO power pins, as shown, for instant cooling! Place in your case, or even better, on top of your Pi's CPU to give it extra air-flow\n\nCompatible with any and all Raspberry Pi computers but only the Pi 3 runs hot enough to benefit from any cooling, when doing intense computations\n\nNote that you do not need a fan for your Pi, as it will automatically adjust its speed to avoid overheating, this is just for people who want to run it at top speed for a long time",
    barcode: '874596325665',
    image: 'product_17.jpg',
    stock: 2,
    price: 190,
    category_id: 1,
    user_id: 1,
    status_id: 1,
  },
    
]